import { Inter as FontSans } from "next/font/google"
import '@radix-ui/themes/styles.css';
import "./globals.css";
import { Theme } from '@radix-ui/themes';
import  { Header }  from '../component/Header'
import { cn } from "@/lib/utils"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
        >  
        <Theme>
        <Header />       
        {children}
        </Theme>
        
      </body>
    </html>
  );
}
